#!/bin/bash
iptables -N Logging
iptables -A INPUT -j Logging
iptables -A Logging -m limit --limit 1/day -j LOG --log-prefix "IPTables-Dropped: " --log-level 4
iptables -A Logging -j RETURN
iptables -A INPUT -s #<your public ipv4 address> -j Logging
iptables -A INPUT -i eth0 -s 127.0.0.0/8 -j Logging
iptables -A INPUT -p icmp -m limit --limit 2/second --limit-burst 2 -j Logging
iptables -A INPUT -p icmp -j Logging
iptables -A INPUT -p tcp -m state --state NEW -m limit --limit 2/second -j Logging
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j Logging
iptables -A INPUT -f -j Logging
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j Logging
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j Logging
iptables -A OUTGOING -p tcp -dport --dport 80 -j ACCEPT
iptables -A INPUT -p tcp -m state --state NEW -m limit --limit 2/second -j ACCEPT
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
iptables -A INPUT -f -j DROP
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP
iptables -A INPUT -p icmp -j DROP
iptables -A INPUT -i eth0 -s 127.0.0.0/8 -j DROP
iptables -A INPUT -s #<your public ipv4 address> -j DROP
